"""Prepare frozen inputs for notebook 08; no new model-selection search or downloads."""
from pathlib import Path
import hashlib,json,platform
import numpy as np
import pandas as pd
from distribution_anatomy import french

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'research/notebook_v8'

def design(m,b):
    m=np.asarray(m);b=np.asarray(b);up=np.maximum(m,0)
    return np.column_stack([np.ones(len(m)),m,up,b,b*m,b*up])

def main():
    OUT.mkdir(parents=True,exist_ok=True)
    manifest=json.loads((ROOT/'data/raw/manifest.json').read_text())
    for name,item in manifest.items():
        assert hashlib.sha256((ROOT/'data/raw'/name).read_bytes()).hexdigest()==item['sha256']
    legs=french('portfolios.zip');mom=french('momentum.zip');market=french('factors.zip')
    d=mom[['Mom']].join(market[['Mkt-RF','RF']]).loc['1964':'2022'].copy()
    d['market']=d['Mkt-RF']+d.RF
    for size,label in [('SMALL','small'),('BIG','big')]:
        d[label+'_long']=legs[size+' HiPRIOR'];d[label+'_short']=-legs[size+' LoPRIOR']
    d['long']=(d.small_long+d.big_long)/2;d['short']=(d.small_short+d.big_short)/2
    d['net']=d.long+d.short
    assert (d.net-d.Mom).abs().max()<.02
    d['sigma']=np.sqrt(d.Mom.pow(2).ewm(alpha=.06,adjust=False).mean())
    d['market_2y']=np.expm1(np.log1p(d.market/100).rolling(504).sum())
    d.to_parquet(OUT/'daily.parquet')
    # Trusted local cache generated by this repository. Verify its original key;
    # notebook itself consumes portable parquet, not pickle and not external code.
    cache=pd.read_pickle(ROOT/'research/expanded_models.pkl')
    fingerprint=hashlib.sha256((ROOT/'scripts/expanded_research.py').read_bytes()+(ROOT/'data/raw/manifest.json').read_bytes()).hexdigest()
    assert cache['fingerprint']==fingerprint,'Evaluation cache is stale; rerun its source experiment explicitly.'
    pred=cache['predictions'];pred=pred.loc[pred.end<=pd.Timestamp('2022-12-31')].copy()
    pred.to_parquet(OUT/'evaluation.parquet')
    weeks=d[['long','short']].resample('W-FRI').sum(min_count=1)
    weeks['market']=d.market.resample('W-FRI').apply(lambda s:np.expm1(np.log1p(s/100).sum())*100)
    end=pd.Series(d.index,index=d.index).resample('W-FRI').max()
    weeks['end']=end;weeks['cutoff']=end.shift()
    weeks['bear']=d.market_2y.reindex(pd.DatetimeIndex(weeks.cutoff)).to_numpy()<0
    weeks=weeks.loc['1974':].dropna()
    scenarios={};grid=np.arange(-5,5.01,.5);rng=np.random.default_rng(20260912)
    for year in range(1990,2023):
        cutoff=pd.Timestamp(year-1,12,31)
        tr=weeks.loc[(weeks.index<=cutoff)&(weeks.end<=cutoff)]
        X=design(tr.market,tr.bear.astype(float));Y=tr[['long','short']].to_numpy()
        coef=np.linalg.lstsq(X,Y,rcond=None)[0]
        boot=[];n=len(tr);block=26
        for _ in range(300):
            starts=rng.integers(0,n-block+1,int(np.ceil(n/block)))
            ix=(starts[:,None]+np.arange(block)).ravel()[:n]
            if np.linalg.matrix_rank(X[ix])==6:boot.append(np.linalg.lstsq(X[ix],Y[ix],rcond=None)[0])
        rows=[]
        for bear in [False,True]:
            Z=design(grid,np.full(len(grid),float(bear)));fit=Z@coef
            draws=np.stack([Z@c for c in boot]);net=draws.sum(axis=2)
            lo,hi=np.quantile(net,[.025,.975],axis=0)
            for i,m in enumerate(grid):
                near=tr.bear.eq(bear)&tr.market.between(m-1,m+1)
                rows.append(dict(market=float(m),bear=bear,long=float(fit[i,0]),short=float(fit[i,1]),
                    net=float(fit[i].sum()),mean_lo=float(lo[i]),mean_hi=float(hi[i]),nearby=int(near.sum()),
                    nearby_last10y=int((near&(tr.end>=cutoff-pd.DateOffset(years=10))).sum())))
        scenarios[str(year)]=dict(fit_cutoff=str(cutoff.date()),training_weeks=n,bootstrap_valid=len(boot),rows=rows)
    (OUT/'scenarios.json').write_text(json.dumps(scenarios,indent=2))
    files=[ROOT/'data/raw'/n for n in ['momentum.zip','portfolios.zip','factors.zip']]
    files += [OUT/'daily.parquet',OUT/'evaluation.parquet',OUT/'scenarios.json',
              ROOT/'research/final_distribution_checks/results.json',ROOT/'research/distribution_panel/results.json',
              ROOT/'research/distribution_panel/monthly_profiles.parquet',ROOT/'research/distribution_anatomy/results.json']
    metadata=dict(scope='Frozen historical illustration; daily cache through 2022-12-30; evaluation through 2022 only',
        evaluation_start=str(pred.start.min().date()),evaluation_end=str(pred.end.max().date()),evaluation_weeks=len(pred),
        source_vintage=manifest,python=platform.python_version(),numpy=np.__version__,pandas=pd.__version__,
        scenario_method='annual previous-Dec31 OLS; 300 attempted 26-week block bootstrap refits; seed 20260912; pointwise mean intervals',
        hashes={str(f.relative_to(ROOT)):hashlib.sha256(f.read_bytes()).hexdigest() for f in files})
    (OUT/'manifest.json').write_text(json.dumps(metadata,indent=2))
    print(f'Prepared {len(d)} daily observations, {len(pred)} evaluated weeks, {len(scenarios)} annual scenario fits.')

if __name__=='__main__':main()
